language: objective-c
osx_image: xcode10.1
# xcode_project: GobanSampleProject/GobanSampleProject.xcodeproj
# xcode_scheme: GobanSampleProjectTests
# xcode_sdk: iphonesimulator
script:
- xcodebuild clean build test -project "GobanSampleProject/GobanSampleProject.xcodeproj" -scheme GobanSampleProject -sdk iphonesimulator12.1 -destination "OS=12.1,name=iPhone X" ONLY_ACTIVE_ARCH=NO
