language: objective-c
osx_image: xcode7.3
# xcode_project: GobanSampleProject/GobanSampleProject.xcodeproj
# xcode_scheme: GobanSampleProjectTests
# xcode_sdk: iphonesimulator
script:
- xcodebuild clean build test -project "GobanSampleProject/GobanSampleProject.xcodeproj" -scheme GobanSampleProject -sdk iphonesimulator9.3 -destination "OS=9.3,name=iPhone 6S Plus" ONLY_ACTIVE_ARCH=NO
